// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkoqolhlxjaukntblagu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrb3FvbGhseGphdWtudGJsYWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTM2NDcsImV4cCI6MjA2NTU4OTY0N30.cL082pzEPalQMYOkkkOt1BGVuX2QJ9c8NEROr_7RRJ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);